name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd C:/Users/backup/Documents/test5/archive-system-new
          git reset --hard
          git pull origin main

      - name: Install dependencies
        run: |
          cd C:/Users/backup/Documents/test5/archive-system-new
          pnpm install

      - name: Generate Prisma Client
        run: |
          cd C:/Users/backup/Documents/test5/archive-system-new
          pnpm prisma generate

      - name: Push Prisma schema
        run: |
          cd C:/Users/backup/Documents/test5/archive-system-new
          pnpm prisma db push

      - name: Build Next.js App
        run: |
          cd C:/Users/backup/Documents/test5/archive-system-new
          pnpm build

      - name: Restart App (PM2)
        run: |
          cd C:/Users/backup/Documents/test5/archive-system-new
          npx pm2 restart archive-system-new
          if ($LASTEXITCODE -ne 0) {
            npx pm2 start "pnpm" --name archive-system-new -- start
          }
