name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd C:/Users/backup/Documents/test5
          git reset --hard
          git pull origin main

      - name: Install dependencies
        run: |
          cd C:/Users/backup/Documents/test5
          pnpm install

      - name: Generate Prisma Client
        run: |
          cd C:/Users/backup/Documents/test5
          pnpm prisma generate

      - name: Push Prisma schema
        run: |
          cd C:/Users/backup/Documents/test5
          pnpm prisma db push

      - name: Build Next.js App
        run: |
          cd C:/Users/backup/Documents/test5
          pnpm build

      - name: Restart App (PM2)
        run: |
          cd C:/Users/backup/Documents/test5
          pm2 restart test5 || pm2 start pnpm --name test5 -- start
