name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: C:\actions-runner\_work\archive-system-new\archive-system-new

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Stop PM2 app (if running)
        run: |
          if (pm2 list | Select-String "archive-system-new") {
            pm2 stop archive-system-new
          } else {
            Write-Output "App not running"
          }

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Push Prisma schema
        run: pnpm prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Next.js App
        run: pnpm build

      - name: Verify build output
        run: |
          if (!(Test-Path ".next")) {
            Write-Error "Build failed - .next directory not found"
            exit 1
          }

      - name: Restart App (PM2)
        run: pm2 startOrReload ecosystem.config.js --update-env
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES: ${{ secrets.JWT_EXPIRES }}
          AUTH_COOKIE_NAME: ${{ secrets.AUTH_COOKIE_NAME }}

      - name: Save PM2 processes
        run: pm2 save

      - name: Check if app is running
        run: |
          Start-Sleep -Seconds 5
          pm2 status
          netstat -ano | findstr :3000
          Test-NetConnection localhost -Port 3000
