name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: C:\actions-runner\_work\archive-system-new\archive-system-new

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Stop PM2 app (if running)
        run: |
          if (pm2 list | Select-String "archive-system-new") {
            pm2 stop archive-system-new
          } else {
            Write-Output "App not running"
          }

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm prisma generate

      - name: Push Prisma schema
        run: pnpm prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Next.js App
        run: pnpm build

      - name: Verify build output
        run: |
          if (!(Test-Path ".next")) {
            Write-Error "Build failed - .next directory not found"
            exit 1
          }

      - name: Restart App (PM2)
        run: |
          $env:NODE_ENV="production"
          $env:DATABASE_URL="${{ secrets.DATABASE_URL }}"
          $env:JWT_SECRET="${{ secrets.JWT_SECRET }}"
          $env:JWT_EXPIRES="${{ secrets.JWT_EXPIRES }}"
          $env:AUTH_COOKIE_NAME="${{ secrets.AUTH_COOKIE_NAME }}"
          pm2 startOrReload ecosystem.config.js --update-env

      - name: Debug PM2 status and logs
        run: |
          Write-Output "=== PM2 Status ==="
          pm2 status
          Write-Output "=== PM2 Describe ==="
          pm2 describe archive-system-new
          Write-Output "=== PM2 Logs (last 30 lines) ==="
          pm2 logs archive-system-new --lines 30 --nostream
          Write-Output "=== Environment Check ==="
          node -v
          Get-Location
          Test-Path ".next"
          Write-Output "=== Manual Test ==="
          node .\node_modules\next\dist\bin\next --version
        continue-on-error: true

      - name: Save PM2 processes
        run: pm2 save

      - name: Check if app is running
        run: |
          Start-Sleep -Seconds 5
          pm2 status
          netstat -ano | findstr :3000
          Test-NetConnection localhost -Port 3000
